# Generated by Django 2.1.2 on 2019-03-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_number', models.CharField(db_column='Employee Number', max_length=32, primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='First Name', max_length=50)),
                ('last_name', models.CharField(db_column='Last Name', max_length=32)),
                ('is_active', models.BooleanField(db_column='Is Active', default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
